// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

error LaunchpegFactory__InvalidImplementation();
error Launchpeg__AuctionAlreadyInitialized();
error Launchpeg__CanNotMintThisMany();
error Launchpeg__CanOnlyMintMultipleOfMaxBatchSize();
error Launchpeg__EndPriceGreaterThanStartPrice();
error Launchpeg__JoeFeeAlreadyInitialized();
error Launchpeg__InvalidAuctionDropInterval();
error Launchpeg__InvalidStartTime();
error Launchpeg__InvalidBatchRevealSize();
error Launchpeg__InvalidJoeFeeCollector();
error Launchpeg__InvalidMaxBatchSize();
error Launchpeg__InvalidAllowlistPrice();
error Launchpeg__InvalidProjectOwner();
error Launchpeg__InvalidPercent();
error Launchpeg__InvalidRevealDates();
error Launchpeg__InvalidRoyaltyInfo();
error Launchpeg__LargerCollectionSizeNeeded();
error Launchpeg__MaxSupplyForDevReached();
error Launchpeg__MaxSupplyReached();
error Launchpeg__AllowlistBeforeAuction();
error Launchpeg__NotEligibleForAllowlistMint();
error Launchpeg__NotEnoughAVAX(uint256 avaxSent);
error Launchpeg__PublicSaleBeforeAllowlist();
error Launchpeg__RevealNextBatchNotAvailable();
error Launchpeg__TransferFailed();
error Launchpeg__Unauthorized();
error Launchpeg__WrongAddressesAndNumSlotsLength();
error Launchpeg__WrongPhase();
